# -- This file is largely adapted from the pre-commit-hooks from lalsuite
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]

      - id: end-of-file-fixer
        stages: [pre-commit]

      - id: check-yaml
        files: ^\.pre-commit-config.yaml$
        stages: [pre-commit]

      - id: check-yaml
        args: [--unsafe]
        files: ^\.gitlab.*\.yml$
        stages: [pre-commit]

      - id: file-contents-sorter
        args: [--unique]
        files: \.gitattributes$
        stages: [pre-commit]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
        stages: [pre-commit]

  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.11.13
  #   hooks:
  #     - id: ruff-check
  #       args: [--exit-non-zero-on-fix, --fix, --show-fixes]
  #       stages: [pre-commit]

  #     # run by CI only, to get code quality report
  #     - id: ruff-check
  #       args: [--exit-zero, --output-file, code-quality-ruff.json, --output-format, gitlab]
  #       stages: [manual]
